"""
Abstract strategy interface.

Strategies generate trading intents (signals) that are submitted to the OMS.
They are decoupled from exchange specifics - they only see normalized
market data and submit OrderIntents.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any

from app.core.enums import OrderSide, OrderType, TimeInForce


@dataclass
class OrderIntent:
    """
    A trading intent generated by a strategy.

    This is NOT an order - it's a request that will go through validation
    and risk checks before becoming an order.
    """
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: Decimal
    price: Decimal | None = None
    time_in_force: TimeInForce = TimeInForce.GTC
    strategy_id: str = ""
    exchange: str = ""  # Target exchange for multi-exchange arb routing
    cancel_order_ids: list[str] = field(default_factory=list)  # Orders to cancel (MM requote)
    metadata: dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """
    Abstract strategy interface.

    Strategies implement on_tick() to react to market data
    and generate OrderIntents. The StrategyRunner manages
    the lifecycle and feeds market data.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique strategy name."""
        ...

    @property
    @abstractmethod
    def strategy_type(self) -> str:
        """Strategy type identifier."""
        ...

    @abstractmethod
    async def on_tick(self, symbol: str, bid: Decimal, ask: Decimal, last: Decimal) -> list[OrderIntent]:
        """
        Called on each market data update.

        Returns a list of OrderIntents to submit. Return empty list for no action.
        """
        ...

    async def on_fill(self, symbol: str, side: str, quantity: Decimal, price: Decimal) -> None:
        """Called when an order from this strategy is filled. Override if needed."""
        pass

    async def on_start(self) -> None:
        """Called when strategy is started. Override for initialization."""
        pass

    async def on_stop(self) -> None:
        """Called when strategy is stopped. Override for cleanup."""
        pass
